### PR TITLE
added Mod chat "/ (text)"

### PR DESCRIPTION
**Pull request by xXAbood**
sounds too old but no one has posted it here yet?.

### CODE REVIEW

**Comment by DrOreo002** [comment]
Isn't it bad to loop through current peers on the server?. Imagine there're 130 players online and server has 3 mods active. So everytime one of those mod do a mod chat, server would need to loop 130 times or maybe even more, depending on how often mod chat is being used.

So I'd suggest to cache peerId if that peer is a mod, cache it into a vector or whtever. Then loop that one instead

**Comment by iProgramMC** [comment]
@DrOreo002 computers are fast nowadays and its unnecessary to optimize at this point. His server is never gonna reach 250 players anyway i believe, its fine

**Comment by xXAbood** [comment]
> @DrOreo002 computers are fast nowadays and its unnecessary to optimize at this point. His server is never gonna reach 250 players anyway i believe, its fine

you probably could see the date of this pull request and write something different since this commit is even closed.

**Comment by iProgramMC** [comment]
Oops

**Pull request closed without merging**
