### PR TITLE
fixed crash when saving worlds

### PR DESCRIPTION
**Pull request by niko1802**

### CODE REVIEW

**Comment by SecretHax** [comment]
Wow, genius..
Removing useful part of code and swearing in comments.

**Comment by SecretHax** [comment]
> _No description provided._

And btw, it prevents corrupting worlds, so get your facts right :D

**Comment by OverallGod** [comment]
Lol I just make them disconnect when worlds save

**Comment by SecretHax** [comment]
> Lol I just make them disconnect when worlds save

Man, if there are 60+ people, executing a loop for 60 peers might make the server crash. Destroying the server-host doesn't make them dc instantly, but since the host is off, the server isn't reacting to the incoming packets ( e.g. when someone edits worlds ), so the worlds aren't getting corrupted.

**Comment by OverallGod** [comment]
@SecretHax then just send them to the world select screen

**Comment by SecretHax** [comment]
> @SecretHax then just send them to the world select screen

Well, it's also 60 packets then lel. It could lag the server, crash and corrupt worlds, that's why this "wtf" thing is better. :D

**Comment by ilyn1337** [comment]
Make a whitelist system and kick off all from the server... All is this

**Comment by SecretHax** [comment]
> Make a whitelist system and kick off all from the server... All is this

Wow, another pseudo-genius. Kicking everyone from the server is also n packets where n is the amount of users online. So it's still useless, cuz the server won't hold so many packets at the same time, crash and corrupt worlds. Still my host destroying solution is better :D

**Comment by playingo** [comment]
just dont remove the code and run server.exe and the python redirect thingy separately, so incase you need to disconnect everyone from the server or do a maintenance break, just add a command into it and when you call this command, everyone will be disconnected and you will close the python redirection and you could make it that it doesnt accept any packets anymore aswell for more security stuff (idk if thats possible, should be) and then close server locally to save worlds without problems.

**Comment by GrowtopiaNoobs** [comment]
This isn't best way to do this. I haven't realized that there is race condition which can cause crash, but it should be solved by another way. Enet resource should be freed. Anyway, you have some chance that you get race condition on world saving, so it would end same. Best way is probably solve this using mutex.

**Comment by GrowtopiaNoobs** [comment]
Good job :+1: but I am going to close this PR now and wait for better one, but thank you.

**Pull request closed without merging**
