### PR TITLE
Growtopia Private server

### PR DESCRIPTION
**Pull request by FarhanGT**
Help me

### CODE REVIEW

**Comment by BerkTheDev** [comment]
bai bai

**Comment by moanhawks** [comment]
oof I wanna die 

Who can stop this man

**Comment by ardakurucim** [comment]
wtf

**Comment by Deveytv** [comment]
@FarhanGT Fp no begging code :man_facepalming: :middle_finger:

**Comment by playingo** [comment]
you wont get shit @FarhanGT ur just another immigrant prob

**Comment by flossboss** [comment]
@farhangt This is pull request not beg for codes. If you can't code I suggest you to go back to GT and scam (you make more profit that way)

**Comment by OverallGod** [comment]
@playingo lol

**Comment by GrowtopiaNoobs** [comment]
This is not real PR...

**Pull request closed without merging**
