### PR TITLE
adding /wizard

### PR DESCRIPTION
**Pull request by OverallGod**
Ok i think i fixed it

### CODE REVIEW

**Comment by ardakurucim** [comment]
@OverallGod Shit update :D

**Comment by OverallGod** [comment]
Eh it's something

**Comment by GrowtopiaNoobs** [comment]
@OverallGod Can you send screenshot (or short walking video) how does it look like? I just want to see it, because it is foreground tile.

**Comment by OverallGod** [comment]
I can't right now. But I can tell you that it looks like a moving wizard block with a name above it.

**Comment by atomiclucky** [comment]
why do you need this lol

**Comment by Cojeb** [comment]
Manually added command into the cpp and built the project (as current pr is super outdated).
It looks like this: @GrowtopiaNoobs 
Screenshot_20200102-014517_Growtopia

**Comment by GrowtopiaNoobs** [comment]
@Cojeb Thank you very much for checking it, I guess I can merge it then.
Also good job to @OverallGod for PR :+1:

**Pull request merged**
