### PR TITLE
/news with txt file 

### PR DESCRIPTION
**Pull request by cmdocmd**
sorry for making other pull request but idk how to change the old one so ye this should remove \r if found

### CODE REVIEW

**Comment by GrowtopiaNoobs** [comment]
Good job :+1: But please make another function which load it fist to some variable and then change function `sendnews`, so that it reads it from that variable. I am wanting you to do this as reading from file is slow and it would cause server to lag. Also there is other stuff, like adding `/news` to `/help` and replacing current code which show news at login with yours new one, but it is not urgent.

Also you can change PR by commiting to your new branch `patch-2` in `cmdocmd/GrowtopiaServer`. Or just click at `Files changed` on top of this page and then click at those three dots above code and click on `Edit file`.

**Comment by cmdocmd** [comment]
check the third commits

**Comment by GrowtopiaNoobs** [comment]
Good job :+1:

**Comment by noobgt** [comment]
Anybody do u mean like news.text like real gt dialogs?

add_label_with_icon|big|Gazette|left|2|
add_spacer|small|
add etc

**Pull request merged**
