### PR TITLE
Added /nick (name)

### PR DESCRIPTION
**Pull request by OverallGod**
if anyone wondered im jordan#0495 on discord ;)

### CODE REVIEW

**Comment by SecretHax** [comment]
You can use also OnChangeName packet, so the user doesn’t need to re-enter world.

**Comment by OverallGod** [comment]
Thanks for the tip!

**Comment by OverallGod** [comment]
Also, can I have permission to work on this project and not publish it?

**Comment by SecretHax** [comment]
>Also, can I have permission to work on this project and not publish it?

@OverallGod What do you mean? Everyone can work with that project and the license says only that before publishing it to all, add GrowtopiaNoobs name. That’s all.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by OverallGod** [comment]
Im just wondering if Im forced to publish what I add @SecretHax

**Comment by SecretHax** [comment]
>Im just wondering if Im forced to publish what I add @SecretHax  ...

@OverallGod just don’t publish your stuff if you don’t want to because you don’t need to
My discord: SecretHax#0001

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by OverallGod** [comment]
I sent you a friend request

**Comment by Mempler** [comment]
The license is AGPL-3.0 Which means:
https://tldrlegal.com/license/gnu-affero-general-public-license-v3-(agpl-3.0)
with the only exception of GrowtopiaNoobs says "Yes, you can use this source without publishing the code, and make a public server."

but you don't have to make PR.

**Comment by SecretHax** [comment]
>The license is AGPL-3.0 Which means: ...

@Mempler 
Can you tell me the full form of PR?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Mempler** [comment]
Pull Requests

**Comment by SecretHax** [comment]
>Pull Requests

@Mempler 
Don’t have to doesn’t mean that you mustn’t do it. People make pull requests to add new commands / fix bugs only if they want to.
Anyways, thank you for the license link, I know the rules only from that what GrowtopiaNoobs told me on discord, but now I gonna read the full license.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by OverallGod** [comment]
yo mempler whats your discord?

**Comment by CrazyMonkey313** [comment]
Cool! If i remove !isVIP will all users be able to use it? As i want all users to use /nick

**Comment by SecretHax** [comment]
>Cool! If i remove !isVIP will all users be able to use it? As i want all users to use /nick

@CrazyMonkey313 mhm

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by CrazyMonkey313** [comment]
> if anyone wondered im jordan#0495 on discord ;)

I've added you on discord- Matty

**Pull request closed without merging**
