### PR TITLE
Changing CDNContent from .txt file

### PR DESCRIPTION
**Pull request by noobes1337**
Hope this time no one will give with a stupid idea like changing cdncontent from a shit.

### CODE REVIEW

**Comment by noobes1337** [comment]
actually not working

**Comment by noobes1337** [comment]
lol

**Comment by ardakurucim** [comment]
@noobes1337 because u are trying to addition string and int

**Comment by noobes1337** [comment]
LOL isn't true. U can easily write to_string(cdncontent) and still doesn't work.

**Pull request closed without merging**
