### PR TITLE
Modified GamePacket packet system, removed asdf strings

### PR DESCRIPTION
**Pull request by NabsiDev**
Ok

### CODE REVIEW

**Comment by NabsiDev** [comment]
also added Packet delay

**Comment by NabsiDev** [comment]
Also now you can use NetID on packets without using memcpy you can just do like this:

Huomautus 2020-05-19 143010

**Comment by SSebia** [comment]
Good job, but why would we need that?

**Comment by NabsiDev** [comment]
idk for Delayed actions like respawn etc

**Comment by noobsteak** [comment]
👍

**Comment by GrowtopiaNoobs** [comment]
Good job :+1:

**Pull request merged**
