### PR TITLE
Better Admin system

### PR DESCRIPTION
**Pull request by OverallGod**
Are you tired of rebuilding the entire project and asking them for a password just to add an admin or set someones level?
Well look no further because I have created the solution just for you this uses the admin level slot thats already in everyone's player data so no need to delete everyone's progress.
**Usage:** 
when you make a command or simply just want to see the players admin level just use this 
``` adminlevel(((PlayerInfo*)(peer->data))->rawName) ```
want an example? here you go 
```
else if (str.substr(0, 4) == "/lol "){		
		if (adminlevel(((PlayerInfo*)(peer->data))->rawName) == 999) {
         // your command here!
}
}
```
If you want to set someones adminlevel just open the players folder find the name and change the thing that says "adminLevel":0
if its in high demand I can create a command that sets someones admin level in game!

### CODE REVIEW

**Comment by flossboss** [comment]
OverallGod, you are a LEGIT LIFE SAVER

**Comment by flossboss** [comment]
I kinda want to help the github community too, going to PR something

**Comment by ZentaiZber** [comment]
lol make script kiddie idiot - 9999

**Comment by herothedev** [comment]
@OverallGod is it possible to make this like `(adminlevel(((PlayerInfo*)(peer->data))->rawName) != 999) break;`?

**Comment by OverallGod** [comment]
Yeah

**Comment by herothedev** [comment]
Okay, thx (my formatting didnt work (on github) still).

**Comment by flossboss** [comment]
👏👍

**Comment by playingo** [comment]
im adding them via config file then type reload in console box (i made it writable in my server) to add them lol

**Comment by herothedev** [comment]
yes but this is lot of easier way to do, and when you do /giverole name level command its overpowered lol.

**Comment by herothedev** [comment]
(that command doesnt exist (yet) but it will exits by me or @OverallGod )

**Comment by herothedev** [comment]
or antobe

**Comment by OverallGod** [comment]
@herothedev  and @flossboss 
im sorry to say but this made it crash when a new player joins.... or runs a command
so here is a fix...

**Comment by OverallGod** [comment]
Oops data/players/ should be players/

**Comment by flossboss** [comment]
I might make a PR for a command on how to give role.

**Comment by herothedev** [comment]
I would already make it, but my vs is broken saddly. so cant test is it working

**Comment by flossboss** [comment]
oof

**Comment by flossboss** [comment]
#753

**Comment by OverallGod** [comment]
Ok I fixed the build error I just needed to include
``` #include <experimental/filesystem> ```

**Comment by flossboss** [comment]
@growtopianoobs you should check this and maybe PR it

**Comment by flossboss** [comment]
build successful

**Comment by FarhanGT** [comment]
### How to add commands /ghost and how to save..
Always debug:(. **Failed**

**Comment by MacaylaMarvelous81** [comment]
nice! it works

**Comment by Avier1** [comment]
image
I don't have a data folder but this happens?

**Comment by GramingFoxTeam** [comment]
image
umm why there is this error?

**Comment by GrowtopiaNoobs** [comment]
Good job :+1: But I merged #1350 which was better in my opinion.

**Pull request closed without merging**
