### PR TITLE
World and SB message for new chat system

### PR DESCRIPTION
**Pull request by Switchry**

### CODE REVIEW

**Comment by flossboss** [comment]
wow b1g

**Comment by GrowtopiaNoobs** [comment]
Can I ask what does this change do? I don't want to download newest GT client and I am a bit lazy to find out myself. :D

**Comment by Switchry** [comment]
> Can I ask what does this change do? I don't want to download newest GT client and I am a bit lazy to find out myself. :D

Theres a new chat system for gt 2.998 and the chat has
Tabs:
- All
-World
- Private
- System
- Custon

So when u sendconsolemsg without the CP_ thing
It will show on System and All tab

And if u use the CP_ its used for chat prefix such like
[W] = World chat
[MSG] Messsage
[SB] Super broadcast
Etc



Sorry for bad grammar and bad explanation

**Comment by GrowtopiaNoobs** [comment]
Interesting. Your explanation is good. :+1: I will check what it looks like on YT later. It would be also cool to find out what `CP, PL and OID` do.

Good job :+1:

**Pull request merged**
