### PR TITLE
Growtopia API

### PR DESCRIPTION
**Pull request by ilyn1337**
# Growtopia Dialogs

To make something is easier, here's the Growtopia PS API. It's including dialog stuff for now. Examples:

Let's declare the dialog by:
```cpp
GTDialog myDialog;
```

Great, now our dialog is defined and ready to use. Now let's add Dialog title with icon:
```cpp
myDialog.addLabelWithIcon("`wMy Dialog Title``", 32, LABEL_BIG);
//Usage: myDialog.addLabelWithIcon(TITLE, ITEM_ID, STYLE);
```
Alright, our title is done. Now lets create some labels: 
```cpp
myDialog.addLabel("Hello, it's my cool dialog!");
//Usage: myDialog.addLabel(TEXT);
```
Now let's add spacer?
```cpp
myDialog.addSpacer(SPACER_SMALL);
//Usage: myDialog.addSpacer(STYLE);
```
Let's finish the dialog:
```cpp
myDialog.endDialog("myDialogName", "Cool", "Nah");
//Usage: myDialog.endDialog(STRING_DIALOG_NAME, ACCEPT, REJECT);
```
Our dialog body is finished! Let's send the dialog to peer:
```cpp
GamePacket p = packetEnd(appendString(appendString(createPacket(), "OnDialogRequest"), myDialog.finishDialog()));
ENetPacket* packet = enet_packet_create(p.data, p.len, ENET_PACKET_FLAG_RELIABLE);
enet_peer_send(peer, 0, packet);
delete p.data;
```

# Items.dat Hash Finder

It's so simple, Just use `GetHashOf("PATH OF ITEMS.DAT");`

It's just some examples, you can add more features by exploring the header file.

### CODE REVIEW

**Comment by jagerrood** [comment]
thanks for sharing!

**Comment by OverallGod** [comment]
Very good work.

**Comment by yikesr** [comment]
Severity	Code	Description	Project	File	Line	Suppression State
Error	C4700	uninitialized local variable 'myDialog' used	ZyMe	3698

**Comment by ilyn1337** [comment]
try to include "GTAPI.h"

**Comment by OverallGod** [comment]
hmm im also getting uninitialized local variable use and yes I did include it. I dont really come a crossed this a lot and I have already tried a couple things. any tips?

**Comment by GrowtopiaNoobs** [comment]
I told to @ilyn1337 what should be changed on code to make it work correctly. If anyone want to use this code rigth now, then fastest way is probs this:
```C++
GTDialog myDialogTmp;
GTDialog* myDialog = &myDialogTmp;
```

**Comment by ilyn1337** [comment]
Yep, changed

**Comment by OverallGod** [comment]
Can you help be with text boxes? I made a text box by looking at the register packet but I'm not sure how the return dialog part works.

**Comment by ilyn1337** [comment]
@OverallGod Send dialog like this? ```myDialog.finishDialog()```

```cpp
GamePacket p = packetEnd(appendString(appendString(createPacket(), "OnDialogRequest"), myDialog.finishDialog()));
ENetPacket* packet = enet_packet_create(p.data, p.len, ENET_PACKET_FLAG_RELIABLE);
enet_peer_send(peer, 0, packet);
delete p.data;
```

**Comment by OverallGod** [comment]
@ilyn1337 I'm sorry that's not what I was talking about I should have just contacted you on discord.  I don't have the brain of a 2 year old I can figure out how to use your great api. I was wondering how to use text boxes and set whatever's in the textbox to a string. This was a different issue that didn't belong here. Sorry for the confusion

**Comment by ilyn1337** [comment]
Juse use like this(example for register): x.addInputBox("pass1 <-This is name of your textbox, server will get this as name in action|dialog_return", "Password: <-This is your left text", "(this is box's text, you can do it like Enter Your Password Here)", 128 <-Maximum chars of textbox);
 
Display will be like this:
```
          ┌───────────────┐
Password: │               │
          └───────────────┘
```
My discord is noob#1337

**Comment by OverallGod** [comment]
Thanks :)

**Pull request merged**
