### PR TITLE
iOS Device Support

### PR DESCRIPTION
**Pull request by ilyn1337**
It should be working, if its not, you can develop XD

### CODE REVIEW

**Comment by OverallGod** [comment]
xD cool beans

**Comment by willi123yao** [comment]
As for the update to the `enet server test.cpp`, there is an errata since after updating, HASH will be undefined and cause building to fail due to missing variables

**Comment by ilyn1337** [comment]
@willi123yao sorry mate, Mempler fixed it.

**Comment by SecretHax** [comment]
>As for the update to the `enet server test.cpp`, there is an errata since after updating, HASH will be undefined and cause building to fail due to missing variables

@willi123yao well, are you healthy? Of course you need to replace it with current hash......

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by willi123yao** [comment]
@SecretHax I mean clearly he just updated the hash in the [other commit](https://github.com/GrowtopiaNoobs/GrowtopiaServer/commit/c842ed54dc6c9be0a2de1f36bd9f3857c5f90cf9) and now he removed the hash which will cause the build to fail **by default**, especially for those new people coming here who do not yet know the code and want to try start making their own server.

**Comment by SecretHax** [comment]
> the

Hahaha, so you think, AMATEUR coders will start private servers and fail debugging because of that "HASH"? Omg you are a clown.

**Comment by SecretHax** [comment]
> @SecretHax I mean clearly he just updated the hash in the [other commit](https://github.com/GrowtopiaNoobs/GrowtopiaServer/commit/c842ed54dc6c9be0a2de1f36bd9f3857c5f90cf9) and now he removed the hash which will cause the build to fail **by default**, especially for those new people coming here who do not yet know the code and want to try start making their own server, and they wouldn't even know the last updated hash from here at all.

Hahaha, so you think, AMATEUR coders will start private servers and fail debugging because of that "HASH"? Omg you are a clown.

**Comment by ilyn1337** [comment]
Ok, just stop trashtalking y'all...

**Pull request merged**
