### PR TITLE
Actual CDNContent for v2.999

### PR DESCRIPTION
**Pull request by noobes1337**

### CODE REVIEW

**Comment by WoofHax** [comment]
I think read new CDN on txt is easily

**Comment by ardakurucim** [comment]
``proto=84|choosemusic=audio/mp3/tsirhc.mp3|active_holiday=9|server_tick=203930170|clash_active=0|drop_lavacheck_faster=1|isPayingUser=0|``

**Comment by playingo** [comment]
cdncontent be like

**Comment by JadlionHD** [comment]
that would be great, Switchry just made the PR #1087 idk i havent try that yet.

**Comment by GrowtopiaNoobs** [comment]
Good job :+1: but I have decided to merge #1087 

@ardakurucim Do you have any more information about this? And can you please wait till holiday ends on GT and make new PR?

**Pull request closed without merging**
