### PR TITLE
Wrench crash fix

### PR DESCRIPTION
**Pull request by Switchry**
fixes crash packet "action|wrench\nnetid||" or something like that which can be used with cheat engine

### CODE REVIEW

**Comment by playingo** [comment]
yeah i've found it a couple months ago and posted it into a issues tab, it should be fixed now.

**Comment by flossboss** [comment]
Great work 👍🏻

**Comment by SteakNeedCpp** [comment]
Thenks now i have b1gger cpp than all

**Comment by flossboss** [comment]
Nice name :v

**Comment by GrowtopiaNoobs** [comment]
Good job :+1:

**Pull request merged**
