### PR TITLE
/demote

### PR DESCRIPTION
**Pull request by flossboss**
Also added /demote to demote players from in-game.

### CODE REVIEW

**Comment by ardakurucim** [comment]
use OnAddNotification for cool thingie lol

**Comment by flossboss** [comment]
lol

**Comment by moanhawks** [comment]
Plz change adminlevel to isSuperAdmin

**Comment by flossboss** [comment]
@moanhawks wdym its supposed to be like this

**Comment by flossboss** [comment]
i'm going to check this again tmr
closing since appveyor shows alot of error

**Pull request closed without merging**
