### PR TITLE
Better breaking blocks & minor improvements

### PR DESCRIPTION
**Pull request by MarmoriPelaa**

### CODE REVIEW

**Comment by noobes1337** [comment]
What the fuck?

**Comment by iProgramMC** [comment]
Awesome job!

**Comment by WoofHax** [comment]
Can you explain what is (int)((tool == 98 || tool == 1438 || tool == 4956) ? 8 : 6); can do for?

**Comment by iProgramMC** [comment]
That is for pickaxes (Enhanced Digging)

**Comment by MarmoriPelaa** [comment]
@WoofHax will probably replace that with something fancier at some point. You could implement fast digging in a different way though. It's just a quick and dirty solution. Also, enjoy collecting the items you have dropped because I implemented that too.

**Comment by WoofHax** [comment]
Awesome

**Comment by iProgramMC** [comment]
Yikes. Appveyor build failed - go to Jobs and Visual Studio 2015 and check the logs for errors.

**Comment by MarmoriPelaa** [comment]
This will probably never merge because I swapped the location of functions :I

**Comment by GrowtopiaNoobs** [comment]
I am unable to check it 100% :D There might be some minor bugs, but I hope when they appear, then there will be PRs from community, that will fix it. @MarmoriPelaa I hope that your coding skills are good and you checked what you PRed.

**Comment by noobes1337** [comment]
ye for some reasons the wl and megaplant can be broken in 1 hit

**Pull request merged**
