### PR TITLE
adding BlockTypes Checkpoint and ClothTypes Ances

### PR DESCRIPTION
**Pull request by MoanHawks**

### CODE REVIEW

**Comment by GuckTubeYT** [comment]
wo + w = wow

**Comment by GuckTubeYT** [comment]
sign pls

**Comment by WoofHax** [comment]
make you self fp
this is blockType not sign code lol

**Comment by GrowtopiaNoobs** [comment]
Good job :+1: but I dont think that artifact belongs to clothes.

**Pull request merged**
