### PR TITLE
Gazette directly from file [CACHING / NO SLOWING DOWN]

### PR DESCRIPTION
**Pull request by herothedev**
You dont need to anymore rebuild your exe for just updating gazette nowdays u can do it by creating news.json file and putting inside of it `{"news":"gazette"}`

### CODE REVIEW

**Comment by NotDark** [comment]
you should use txt

**Comment by herothedev** [comment]
Ye i tried but then gazette empty idk why

**Comment by NotDark** [comment]
> Ye i tried but then gazette empty idk why

remove \n from the txt

**Comment by herothedev** [comment]
kk lemme try later after i come from school

**Comment by MacaylaMarvelous81** [comment]
if you wanna use txt files and get newlines and spaces use
```C++
std::ifstream news("news.txt");
std::stringstream buffer;
buffer << news.rdbuf();
std::string newsString(buffer.str());
```
and send `newsString` in the packet
haven't tested using stuff like \n, i just replaced those with new lines

**Comment by herothedev** [comment]
so this makes that u can use \n AND u can too use by making new line manually?

**Comment by MacaylaMarvelous81** [comment]
it probably works with \n cuz string but i havent tested, i just replaced my \n with manual new line and it works

**Comment by herothedev** [comment]
k

**Comment by Cojeb** [comment]
I suggest moving news.json contents to just a new key in config.json, no reason to have so many files or folders (this problem can be seen around private servers).

**Comment by herothedev** [comment]
this is old pr...

**Pull request closed without merging**
