### PR TITLE
Big optimization changes & memory leak fixes.

### PR DESCRIPTION
**Pull request by loanselot**
Hello, im from turkey im 17 years old and im coding c# c++ im like kidding with other skids. They think im kids but im just kidding with they and laughing.

### CODE REVIEW

**Comment by Ipadtopia** [comment]
😂

**Comment by SSebia** [comment]
Close This Trash

**Comment by xXAbood** [comment]
> Close This Trash

how fucking dare u its the best pr

**Comment by noobes1337** [comment]
that will actually optimize the server

**Comment by loanselot** [comment]
> Close This Trash

Yo sethmumu rebirther aap bypass selling 1 wl LEL SO CHEAP gogogogogogo /fp.......................................... /cheers i love gt

**Comment by xXAbood** [comment]
https://github.com/xXAbood/BexpgSimulator

**Comment by noobsteak** [comment]
I already adding this to my ccp and it is are fast the code and worked.

**Comment by LorenzoGTPH** [comment]
bExpG.eXe.SQUaD.NeT

**Comment by GrowtopiaNoobs** [comment]
Please stop trolling

**Comment by Bexpg** [comment]
Thx its big fixes

**Pull request closed without merging**
