### PR TITLE
Added /find (itemname)

### PR DESCRIPTION
**Pull request by SecretHax**
Added /find (itemname). Well yeah, it's beta. Can someone make the itemname and def.name lowercase? Because for now the user can't type for example legendary wings. He needs to type Legendary Wings.

### CODE REVIEW

**Comment by Tryp0** [comment]
noice

**Comment by ritzysw** [comment]
you can use PlayerDB::getProperName (for both itemname and def.name) and use .find("") != string::npos

**Comment by SecretHax** [comment]
> you can use PlayerDB::getProperName (for both itemname and def.name) and use .find("") != string::npos

`					else if (str.substr(0, 6) == "/find ")
					{
						ItemDefinition def;
						bool found = false;
						string itemname = str.substr(6, cch.length() - 6 - 1);
						for (int o = 0; o < 7196; o++)
						{
							def = getItemDef(o);
							if (PlayerDB::getProperName(def.name) == PlayerDB::getProperName(itemname))
							{
								GamePacket p344 = packetEnd(appendString(appendString(createPacket(), "OnConsoleMessage"), "`rItem ID of " + def.name + ": " + std::to_string(def.id)));
								ENetPacket * packet344 = enet_packet_create(p344.data,
									p344.len,
									ENET_PACKET_FLAG_RELIABLE);
								enet_peer_send(peer, 0, packet344);
								delete p344.data;
								found = true;
							}
						}
						if (found == false)
						{
							GamePacket p3344 = packetEnd(appendString(appendString(createPacket(), "OnConsoleMessage"), "`4Could not find the following item. Please use uppercase at the beggining, ( for example: Legendary Wings, not legendary wings )."));
							ENetPacket * packet3344 = enet_packet_create(p3344.data,
								p3344.len,
								ENET_PACKET_FLAG_RELIABLE);
							enet_peer_send(peer, 0, packet3344);
							delete p3344.data;
						}
						found = false;
					}`
Thanks for help. That worked.

**Comment by ritzysw** [comment]
also instead of using
`for (int o = 0; o < 7196; o++)`
you can use
`for(int o = 0;o < itemDefs.size();i++)` so you don't have to update "7196" number every time

**Pull request merged**
