### PR TITLE
edit variable name on SendDrop

### PR DESCRIPTION
**Pull request by MoanHawks**

### CODE REVIEW

**Comment by arshizx** [comment]
For What lol

**Comment by MoanHawks** [comment]
idk

**Comment by GuckTubeYT** [comment]
thanks yey

**Comment by DrOreo002** [comment]
Did you just renamed the variable name?

**Comment by MoanHawks** [comment]
Yes

**Comment by ardakurucim** [comment]
lol useless

**Comment by MoanHawks** [comment]
@ardakurucim if useless then dont look it bcz this only for indo only not for you

**Comment by cmdocmd** [comment]
wtf you did u just made instead of int count int dropamount really???

**Comment by MoanHawks** [comment]
> wtf you did u just made instead of int count int dropamount really???

then should i call int amount?

**Comment by noobes1337** [comment]
not gonna comment

**Pull request closed without merging**
