### PR TITLE
Disconnect fix

### PR DESCRIPTION
**Pull request by ardakurucim**

### CODE REVIEW

**Comment by GrowtopiaNoobs** [comment]
I think that original gt does that to load items after update. Try to check it and tell me if I am mistaken.

**Comment by ardakurucim** [comment]
I didnt check but i dont think it does

**Comment by ardakurucim** [comment]
Because we're not able to join game for now

**Comment by MoanHawks** [comment]
that point was re check the items.dat peer file so no need to remove it

**Comment by GrowtopiaNoobs** [comment]
Then it probably might be problem with some of those new PRs. If you got some time, then you can try to find real bug by trying when it will stop working. https://www.metaltoad.com/blog/beginners-guide-git-bisect-process-elimination  Good commit should be `57c0643` and you can probably mark newest as bad, so `d22f5eb`. If the code doesnt compile use the `git bisect skip`.

**Comment by ardakurucim** [comment]
@GrowtopiaNoobs when i tried to remove it. It worked somehow thats why i PRed it

**Comment by GrowtopiaNoobs** [comment]
I should probably merge it then, but then we will forget that there was some other real problem. So I am not really sure what to do now. It is probably some bug with hash.

**Comment by noobsteak** [comment]
Growtopia cache packet (OnSuperMain) has a 6th parameter. It's another hash.

**Comment by GrowtopiaNoobs** [comment]
@noobsteak Then please make PR and add it. Also when there is new hash, then I guess there will be some new file, so it would be interesting to know what it is.

So this bug has appeared from new GT client cuz of that new hash and not of cuz those new merged PRs?

**Comment by noobsteak** [comment]
I'm not sure. Also according to @playingo2006, it's "cache location hash" but it could also possibly be the new player_attributes.dat file hash.

**Comment by GrowtopiaNoobs** [comment]
And does anyone know what this file actually contain or can you post it here? Also it should be possible to check to what file this hash belongs by extracting this hash by GT bot and then trying to hash GT files and see if the hash matches.

**Comment by ardakurucim** [comment]
@GrowtopiaNoobs some of the people cannot see parameter 6

also new file just have few things some youtubers name

**Comment by playingoDEERUX** [comment]
@GrowtopiaNoobs We had removed it too, seems like no complains did occur, for us atleast.

**Comment by GrowtopiaNoobs** [comment]
I am going to merge this then and I hope that someone would be able to provide full fix.

**Pull request merged**
