### PR TITLE
Main Door Exit Label

### PR DESCRIPTION
**Pull request by noobes1337**
memcpy lelelele k

### CODE REVIEW

**Comment by RestarkGTINDOG** [comment]
1337 army 4 ever

**Comment by herothedev** [comment]
lelellele forgot struct BlockVisual

**Comment by Zlarex** [comment]
Crash, hmm...

**Comment by noobes1337** [comment]
Closing, making another one b1tches

**Comment by Zlarex** [comment]
I tried again, it's work

**Pull request closed without merging**
