### PR TITLE
Auto Creating Config.json (Worth it?)

### PR DESCRIPTION
**Pull request by GuckTubeYT**
Auto Creating Config.json
Worth it?

### CODE REVIEW

**Comment by GuckTubeYT** [comment]
hmmmmm io.h for mac os x?

**Comment by JUSTNUB** [comment]
> Auto Creating Config.json
> Worth it?

useless

**Comment by Bexpg0** [comment]
Good Job

**Comment by GuckTubeYT** [comment]
> > Auto Creating Config.json
> > Worth it?
> 
> useless

Ouh okay

**Comment by cmdocmd** [comment]
good job but why u made this
cout << "Config Has Been Fixed! Please Reopen This Application";
just make it with out reopen the exe

**Comment by GuckTubeYT** [comment]
> good job but why u made this
> cout << "Config Has Been Fixed! Please Reopen This Application";
> just make it with out reopen the exe

Hehehe okay

**Comment by noobes1337** [comment]
nice job but why the the build failed?

**Comment by GuckTubeYT** [comment]
> nice job but why the the build failed?

Thats because macos

**Comment by GuckTubeYT** [comment]
> nice job but why the the build failed?

io.h not found at mac os x

**Comment by GuckTubeYT** [comment]
ups wait

**Comment by GuckTubeYT** [comment]
Windows And Linux work, except macos didnt work because io.h

**Comment by GrowtopiaNoobs** [comment]
Good job :+1:

**Pull request merged**
