### PR TITLE
/news

### PR DESCRIPTION
**Pull request by triple14**
/news command, cannot test as when I do  add anything it gives me 400 errors on nothing related to stuff I add

### CODE REVIEW

**Comment by Faxtos** [comment]
How about function for external news.json

**Comment by triple14** [comment]
Added Compatibility for that, If you don't want to use the news.json just remove the // from the lines of code except `//delete p.data;`

**Comment by FocusedSG** [comment]
Lol what for creating gamepacket and deleting it? Just omit the whole thing and sendGazette

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by moanhawks** [comment]
Try use txt and get the line

**Comment by herothedev** [comment]
My pr was updated, i added caching. So now you dont need to worry will it slow down the server, thx to gtnoobs.

**Comment by GrowtopiaNoobs** [comment]
Closing this as there is missing funtion `sendGazette` and also it contains code of other PR, which is broken.

**Pull request closed without merging**
