### PR TITLE
Actual fix for disconnect when login

### PR DESCRIPTION
**Pull request by noobsteak**
I've tested the code and works perfectly.

### CODE REVIEW

**Comment by bexpg1377** [comment]
This for what?

**Comment by Surekings** [comment]
gud

**Comment by GrowtopiaNoobs** [comment]
I have looked at it, but you solved it by removing updating of items.dat at all. So there will be problem if server switches to new items.dat, then client will stay at old version so it can lead into unknown bugs.

Thank you, but I think that another solution is needed.

**Comment by noobsteak** [comment]
No, it was because the hash was saved in a wrong integer type. I also removed extra code that was just repeat.

**Comment by bexpg1377** [comment]
Trash

**Comment by GrowtopiaNoobs** [comment]
I checked everything twice and I am unable to find where is the `itemsDat` variable set. This variable is used to send items.dat update to client.

**Comment by noobsteak** [comment]
The ItemsDat variable set is replaced with data from Dark's PR.

**Comment by GrowtopiaNoobs** [comment]
We are probably not understanding each other. Dark did change loading items info from items.dat instead of CoreData.txt. There weren't any changes about items.dat updating. Check your file https://github.com/GrowtopiaNoobs/GrowtopiaServer/blob/0ff214fabcf85c2ce782cafd0d95e37df1d41054/enet%20server%20test/enet%20server%20test.cpp and find any place where is value assigned to `itemsDat` (except that 0 value).

**Comment by RRRRRRa** [comment]
add
```cpp
itemsDatSize = size;
itemsDat = new BYTE[size + 60];
itemsDat[0] = 4;
itemsDat[4] = 16;
itemsDat[8] = 255;
itemsDat[9] = 255;
itemsDat[10] = 255;
itemsDat[11] = 255;
itemsDat[16] = 8;

memcpy(itemsDat + 56, &size, 4);
memcpy(itemsDat + 60, data, size);
```
on line 1281 after / before pData

**Comment by noobsteak** [comment]
I'll be remaking this pr

**Comment by Bexpg0** [comment]
Ok

**Comment by Bexpg0** [comment]
Noob

**Pull request closed without merging**
