### PR TITLE
Giving adminlevel from in game.

### PR DESCRIPTION
**Pull request by flossboss**
This code has not been tested YET. Might have small errors.

========================================

Used to give adminlevel through in game basically works like this:

`/adminlevel playername playeradminlevel`

For example:
`/adminlevel test 999` will give `test` an adminlevel of `999`.

NOTE: This requires #740

### CODE REVIEW

**Comment by yua11** [comment]
your code have something wrong yea

**Comment by moanhawks** [comment]
He using adminlevel for checking cmd 
Try change adminlevel to isSuperAdmin

**Comment by flossboss** [comment]
@yua11 do u have #740?

@moanhawks this is using OverallGod's thing so with the command u have to use ```adminlevel```

**Comment by coldtopia** [comment]
so many error :/

**Comment by flossboss** [comment]
Did you use OverallGod's better admin system?

**Comment by flossboss** [comment]
I haven't tested the code yet.. you should tell me what "error" it is so I can fix it and not complain that there's alot of "errors".

**Comment by coldtopia** [comment]
> Did you use OverallGod's better admin system?

Yes

**Comment by flossboss** [comment]
i'm going to check this again tmr
closing since appveyor shows alot of error

**Pull request closed without merging**
