### PR TITLE
/givesuperadmin

### PR DESCRIPTION
**Pull request by flossboss**
Used to give adminlevel 999 through a command.

### CODE REVIEW

**Comment by flossboss** [comment]
Took forever to find how to pull request on phone... I typed all this through phone haven't checked if it works or not.

**Comment by herothedev** [comment]
maybe use 2 sub strs to choose what admin level to give?

**Comment by flossboss** [comment]
aight ima try that later

**Comment by Deveytv** [comment]
Btw it much error, Fix it first and then Make PR.

**Comment by herothedev** [comment]
What errors? Screenshot them, did u even install this: #740 ?

**Comment by Deveytv** [comment]
> What errors? Screenshot them, did u even install this: #740 ?

Hmm DM me at discord Suking......... Srvr SF you know lah

**Comment by flossboss** [comment]
@DeveyTV you need OverallGod's admin thing...

**Comment by herothedev** [comment]
#740

**Comment by flossboss** [comment]
#753

**Comment by Deveytv** [comment]
@herothedev @flossboss 
image remove data/?

**Comment by flossboss** [comment]
yes unless you have data folder

**Pull request closed without merging**
