### PR TITLE
Added admin special colored text

### PR DESCRIPTION
**Pull request by ardakurucim**
If anything is wrong tell me. Or fix it urself cuz im new at this language .d

### CODE REVIEW

**Comment by ardakurucim** [comment]
delete one of the } becauze i wrote it more

**Comment by ardakurucim** [comment]
Delete last } because i wrote it more.

**Comment by GrowtopiaNoobs** [comment]
I would suggest to simplify this code to:
```C++
if (getAdminLevel(((PlayerInfo*)(peer->data))->rawName, ((PlayerInfo*)(peer->data))->tankIDPass) >= 1) {
	message = "`^" +  message;
}
```
And also admin with level 1 should get colored text too, so you should probably use operator `>=`.

**Comment by ardakurucim** [comment]
@GrowtopiaNoobs I'm new thanks for tip.

**Pull request closed without merging**
