### PR TITLE
ontextbubble signs example

### PR DESCRIPTION
**Pull request by bykoi**
Here's example of ontextbubble signs, you can modify it however you want, if you get some errors, glitchs about that code feel free to ping me in the pull request.

### CODE REVIEW

**Comment by Deveytv** [comment]
> Here's example of onbubbletext signs, you can modify it however you want, if you get some errors, glitchs about that code feel free to ping me in the pull request.

When i put 1 line code at ur cpp there have error can Help me at discord?

**Comment by cmdocmd** [comment]
its not working it make server crash why ???

**Comment by moanhawks** [comment]
@cmdocmd bcz com1 is save to txt

**Comment by Deveytv** [comment]
> its not working it make server crash why ???

Fp, make folder name signs

**Comment by Bykosw** [comment]
@cmdocmd you have to make folder called "signs"

**Comment by cmdocmd** [comment]
i have signs folder but when i enter world it crash when i added this

**Comment by MarmoriPelaa** [comment]
The amount of errors in the AppVeyor build though..

**Comment by VyteGTPS** [comment]
> i have signs folder but when i enter world it crash when i added this

playingo ?????????

**Comment by GrowtopiaNoobs** [comment]
@Bykosw Good job :+1: but you have alot of errors in your code and you don't have any caching for signs.

**Comment by GrowtopiaNoobs** [comment]
Closing this, because of reasons I mentioned and there were classical signs discovered.

**Pull request closed without merging**
