### PR TITLE
/warp /warpto

### PR DESCRIPTION
**Pull request by Hades3235**
ignore the other commits like /ban /howgay,they arent in the code only warp and warpto

### CODE REVIEW

**Comment by ardakurucim** [comment]
/find is broken when i press get it gives nothing

**Comment by jagerrood** [comment]
> /find is broken when i press get it gives nothing

you need to make button function for it on like worldPrivate
(if btn == "get") etc

**Comment by jagerrood** [comment]
> m

would be good if player also rejected to login game like "you are banned" but still good job

**Comment by ardakurucim** [comment]
@jagerrood thank you

**Comment by jagerrood** [comment]
> @jagerrood thank you

any time.

**Comment by ardakurucim** [comment]
@jagerrood i have a question what do I use to send the selected item to the inventory

**Comment by ardakurucim** [comment]
@jagerrood item.itemId = atoi(?)

**Comment by OverallGod** [comment]
@jagerrood  when you use btn =="get" you could use a substr and add the item I'd onto the name of the button like get242 and the substr part would get 242. Its really easy to do. I might pull request it idk

**Comment by OverallGod** [comment]
Btw I really really hate people that steal others code

**Comment by triple14** [comment]
> @jagerrood  when you use btn =="get" you could use a substr and add the item Id onto the name of the button like get242 and the substr part would pull the  242. Its really easy to do. I might pull request it idk

sure do it, cas I've tried it and I cannot get it to work :/

**Comment by triple14** [comment]
> @jagerrood  when you use btn =="get" you could use a substr and add the item Id onto the name of the button like get242 and the substr part would pull the  242. Its really easy to do. I might pull request it idk

That'd be nice, i'm having issues , I've tried to do this but its not workin.

**Pull request closed without merging**
