### PR TITLE
Fixing the unfixable - adding chat filtering

### PR DESCRIPTION
**Pull request by Cojeb**
Changes:
- You can not send empty messages anymore.
- All space from start and end of the string is auto-removed.
- All the extra space from in between characters/words in chat is auto-removed.

All builds are passing. :+1:

### CODE REVIEW

**Comment by GrowtopiaNoobs** [comment]
Good job :+1: But can you explain to me why have you removed setting world to `EXIT` when player leaves world?

**Comment by Cojeb** [comment]
That was accidentally removed and is not supposed to be a part of this PR.

**Comment by Cojeb** [comment]
Good to go.

**Comment by Cojeb** [comment]
@GrowtopiaNoobs

**Comment by GrowtopiaNoobs** [comment]
Thank you

**Pull request merged**
