### PR TITLE
Fixed Server give a 404 error not found

### PR DESCRIPTION
**Pull request by JadlionHD**
#964

### CODE REVIEW

**Comment by zhenshaxx** [comment]
ok pro

**Comment by JadlionHD** [comment]
idk but hopely helped with this

**Comment by arshizx** [comment]
CDNContent24 is newest

**Comment by moanhawks** [comment]
Just use gt bot to see newest

**Comment by herothedev** [comment]
@arshizx nope.

**Comment by herothedev** [comment]
@moanhawks u can get it more easier lol just go uodate gt nd see it

**Comment by NotDark** [comment]
use ce and scan CDNContent to get new

**Comment by JadlionHD** [comment]
i'm using CDNContent24 and it's actually working

**Comment by GrowtopiaNoobs** [comment]
Good job :+1: I am lazy to check if it is correct, so it would be cool if someone opens PR every time there is new version and ppl would comment if it is correct.

**Comment by JadlionHD** [comment]
I think every Growtopia updating the version, ex "2.998" the CDNContent will changed too. well i dont know.

**Comment by Granger-spec** [comment]
@jadlionhd How do u use CDNContent

**Comment by JadlionHD** [comment]
> @JadlionHD How do u use CDNContent

First you need to do is CTRL + F, then search CDNContent, there is should be CDNContent3 idk, now you change it into CDNContent24 or 25 (Haven't test 25 yet). and you're done, there is no more 404 error anymore.
Sorry for the grammar

**Pull request merged**
