### PR TITLE
Added color changing from options.

### PR DESCRIPTION
**Pull request by ardakurucim**
omg pro c0der?

### CODE REVIEW

**Comment by xXAbood** [comment]
shutfkup

**Comment by ardakurucim** [comment]
@xXAbood no u

**Comment by WoofHax** [comment]
has_digit_only 😂 nice programming C++

**Comment by MarmoriPelaa** [comment]
Just change id to unsigned so you don't have to deal with any extra cases. Also, bots could potentially set their color to any of these.
So what I would do is check the colors against a valid vector of *unsigned* integers containing the colors.

**Comment by ardakurucim** [comment]
@MarmoriPelaa There is a packet called OnChangeSkin which doesnt need unsigned integers i didnt know that when i pull requested

**Pull request merged**
