### PR TITLE
Auto get items.dat hash from item.dat file

### PR DESCRIPTION
**Pull request by NotDark**
Thank for this #173

### CODE REVIEW

**Comment by NotDark** [comment]
Thank for this #173

**Comment by FKSP** [comment]
Good job, I also wanted to add this but I'm busy right now.

**Comment by FuzionVapes** [comment]
It gives me error

**Comment by NotDark** [comment]
> It gives me error

that is work for me and what error?

**Comment by FuzionVapes** [comment]
When trying to compile it

**Comment by NotDark** [comment]
> When trying to compile it
yes........but what the error

**Comment by FuzionVapes** [comment]
Already Fixed

**Comment by vonsogt** [comment]
> It gives me error

add this "#pragma warning(disable : 4996)"

**Comment by Yoayao** [comment]
in where

**Comment by fargamer** [comment]
how to fix this error
Severity	Code	Description	Project	File	Line	Suppression State
Error	C4996	'fopen': This function or variable may be unsafe. Consider using fopen_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.	enet server test \growtopiaserver-master\baka\enet server test\enet server test.cpp	2228

**Comment by herothedev** [comment]
Works for me, thanks Dark :)

**Comment by vonsogt** [comment]
> in where

You can put at first line too or outside of function
"#pragma warning(disable : 4996)"

**Pull request merged**
