### PR TITLE
MODSB Command.

### PR DESCRIPTION
**Pull request by NoobesGT**
Like normal sb but as world is HIDDEN. And just for mods.

### CODE REVIEW

**Comment by ardakurucim** [comment]
@NoobesGT There is /jsb command why did you add this .d

**Comment by NoobesGT** [comment]
its for mods?

**Comment by ardakurucim** [comment]
@NoobesGT But jsb is public and it do same thing too

**Comment by NoobesGT** [comment]
yes and because when you do a jsb or a sb the name of a mod is not with @ i made this just for mods!

**Comment by RajehTXD** [comment]
just add Mod-SB intead of Super- Broadcast, It would make sense to use

**Comment by RajehTXD** [comment]
then disable jsb

**Pull request closed without merging**
