### PR TITLE
Added Linux compatibility.

### PR DESCRIPTION
**Pull request by MarmoriPelaa**
Added Linux compatibility which was requested by some users. Please note that you have to compile ENet yourself. Based on an older server which was heavily edited. Compiles with -std=c++11.

### CODE REVIEW

**Comment by mkevinam** [comment]
How?

**Comment by ZentaiZber** [comment]
where i can get enet.exe

**Comment by ZentaiZber** [comment]
we need to compile enet server cpp on linux?

**Comment by MarmoriPelaa** [comment]
@ZentaiZber You should compile on Linux with g++. DO NOT USE WINE. IT'S FULLY LINUX!

**Comment by ZentaiZber** [comment]
how? i dont know

**Comment by ZentaiZber** [comment]
like 6hours i trying to compile with ma frend :(

**Comment by ZentaiZber** [comment]
so its not need .exe?

**Comment by OverallGod** [comment]
Lol

**Comment by OverallGod** [comment]
If you use g++ to compile it. It will create a file called a.out unless you tell it to output with a different name. You would cd into the folder then run ./a.out just change a.out to the name of the built file if you changed it. If it gives you an error you might need to mark it as executable

**Comment by ZentaiZber** [comment]
what?

**Comment by ZentaiZber** [comment]
> `In file included from stdafx.h:8,
                 from enet server test.cpp:20:
targetver.h:8:10: fatal error: SDKDDKVer.h: No such file or directory
 #include <SDKDDKVer.h>
          ^~~~~~~~~~~~~
compilation terminated.
`

???

**Comment by ZentaiZber** [comment]
ah fk i dont know linux i will buy vps win sad you

**Comment by herothedev** [comment]
@ZentaiZber This is so easy.. 

### Linux
1. Make sure you have the build tools ready for installation. You can download them depending on your distribution.
  * For Ubuntu or Debian-based distributions, simply open a terminal window and type in the command (`$ sudo apt-get install build-essential`)
  * Other distributions, please refer to your package manager and install the one containing g++ and gcc
2. Install ENet from here (http://enet.bespin.org/Installation.html)
3. Clone or download this project and open a terminal window in that folder.
4. Run this command to build the server executable (`$ g++ -o enet server test enet server test.cpp -std=c++11 -lenet`)
5. Now you have your working executable, follow instructions from the [wiki here](https://github.com/GrowtopiaNoobs/GrowtopiaServer/wiki/Basic-setup#setting-up-http-server) to setup your server
6. Start the server by opening terminal window in new server folder and running `$ ./enet server test`
(tutorial taken from @willi123yao 's repo, thanks to him and i edited it little bit. + i never compiled on linux, so idk will this work)

**Comment by ZentaiZber** [comment]
> @ZentaiZber This is so easy..
> 
> ### Linux
> 1. Make sure you have the build tools ready for installation. You can download them depending on your distribution.
> 
> * For Ubuntu or Debian-based distributions, simply open a terminal window and type in the command (`$ sudo apt-get install build-essential`)
> * Other distributions, please refer to your package manager and install the one containing g++ and gcc
> 
> 1. Install ENet from here (http://enet.bespin.org/Installation.html)
> 2. Clone or download this project and open a terminal window in that folder.
> 3. Run this command to build the server executable (`$ g++ -o enet server test enet server test.cpp -std=c++11 -lenet`)
> 4. Now you have your working executable, follow instructions from the [wiki here](https://github.com/GrowtopiaNoobs/GrowtopiaServer/wiki/Basic-setup#setting-up-http-server) to setup your server
> 5. Start the server by opening terminal window in new server folder and running `$ ./enet server test`
>    (tutorial taken from @willi123yao 's repo, thanks to him and i edited it little bit. + i never compiled on linux, so idk will this work)

i hope this work

**Comment by ZentaiZber** [comment]
Thx you bro :)

**Comment by ZentaiZber** [comment]
hmm wear clothes not work

**Comment by herothedev** [comment]
make sure CoreData is right, and if it is it is your code fault.

**Comment by ZentaiZber** [comment]
Windows is not bug but i use linux and the clothes bug

**Comment by MarmoriPelaa** [comment]
> Windows is not bug but i use linux and the clothes bug

I would repeat what @herothedev said.

**Comment by GrowtopiaNoobs** [comment]
Can someone please check, that this compiles under windows? Thank you

**Comment by MarmoriPelaa** [comment]
It should compile on Visual Studio for both Windows and Linux. Going to check when I get back home.

**Comment by GrowtopiaNoobs** [comment]
I made CI work and it shows that there is missing function `_getch()`. https://ci.appveyor.com/project/GrowtopiaNoobs/growtopiaserver/builds/26783103/messages

**Comment by OverallGod** [comment]
@GrowtopiaNoobs I had to do some things with the fixcolor part. I dont really remember and I haven't tested it on windows yet

**Comment by MarmoriPelaa** [comment]
Alright, so I haven't tested yet but you should try getchar from stdio.h. It's the same as getch but it's for Linux.
I haven't tested the following code:
```C++
#ifdef __linux__
#include <stdio.h>
char _getch() {
    return getchar();
}
#endif
```

**Comment by GrowtopiaNoobs** [comment]
I had that issue with `_getch` on windows. Right now I am having issues with headers on linux. You can check CI to see what is going on.

**Comment by MarmoriPelaa** [comment]
Alright, I am not entirely sure but it could be with the compiler understanding the file types the wrong way. I'm pretty sure the fix to this is to rename the extensions of .c to .cpp
Example: bcrypt.c becomes bcrypt.cpp
If the issue persists:
- In Visual Studio, please set the C Compiler AND C++ Compiler to g++ when building for Linux.
- Rename wrapper.c to ow-crypt.cpp

**Comment by GrowtopiaNoobs** [comment]
Hurray! We did it :D

**Pull request merged**
