### PR TITLE
Fix for consummables

### PR DESCRIPTION
**Pull request by SecretHax**
Hey guys! Here is a fix for consummables. Before you could place them like regular blocks and even place those items on locks what was really concerning after the lock disappeared. In my fix, you can't place consummables in any area.

### CODE REVIEW

**Comment by OverallGod** [comment]
That's cool beans

**Comment by OverallGod** [comment]
I'm actually really glad you've been active on pr's

**Comment by SecretHax** [comment]
@OverallGod Thanks for supporting meh ;)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by willi123yao** [comment]
btw consummables is actually spelt as consumables, and there are a few redundant lines of code in the PR (like the last if statement, you could have combined it with the previous if by returning from there, and not much use for the variable llek unless you planning to add seed support but clearly not in this PR)

**Comment by SecretHax** [comment]
> btw consummables is actually spelt as consumables, and there are a few redundant lines of code in the PR (like the last if statement, you could have combined it with the previous if by returning from there, and not much use for the variable llek unless you planning to add seed support but clearly not in this PR)

Well, ask nenkai why he wrote "consummables" instead of "consumables" in his item database, not my fault hah. And yeah, that's my messy code full of useless variables which you don't even need to read son ;)

**Pull request merged**
