### PR TITLE
Important save fixes

### PR DESCRIPTION
**Pull request by ilyn1337**
Big server crasher a.k.a playingo's 'memcpy' way. wow

### CODE REVIEW

**Comment by noobesgt** [comment]
B1g fix

**Comment by playingo** [comment]
a

**Comment by playingo** [comment]
now fix action|wrench|netid changing ce string after wrench putting the "|" symbol twice use filter stuff for that. also third way with action|enter_game then u have the stuff

**Comment by GrowtopiaNoobs** [comment]
Good job :+1:

**Pull request merged**
