### PR TITLE
Update to 2.983

### PR DESCRIPTION
**Pull request by NotDark**
Change  "OnSuperMainStartAcceptLogon

### CODE REVIEW

**Comment by NotDark** [comment]
> Completely wrong lol

that work fine for me can you say what wrong

**Comment by NeedHelpUrgents** [comment]
> Change "OnSuperMainStartAcceptLogon

works but stuck on login screen how fix

**Comment by NotDark** [comment]
> > Change "OnSuperMainStartAcceptLogon
> 
> works but stuck on login screen how fix

Update your growtopia to 2.983
and get newest items.dat from you growtopia folder

**Comment by GrowtopiaNoobs** [comment]
It should probably work, I will check it tommorow.

**Comment by NeedHelpUrgents** [comment]
Thanks bro, now i can play new Growtopia with new sprites :D

**Comment by GrowtopiaNoobs** [comment]
Nice, it works. I have updated wiki link to newest items.dat.

**Comment by Zfee** [comment]
where can i get the v2.932

**Pull request merged**
