### PR TITLE
Fix of crash server

### PR DESCRIPTION
**Pull request by mar4ello6**
I had atack, that created many world with long random names... So, I wrote that. If what my English isn't very good and I'm not pro at codding, so if you found error write it here please. 😃

### CODE REVIEW

**Comment by Yoayao** [comment]
omg it so helpfull thanks you for share

**Comment by Yoayao** [comment]
btw it have something wrong on enet_peer_disconnect_later(peer, 0)

**Comment by Yoayao** [comment]
before 
sendConsoleMsg(peer, "`4Sorry, but world names with more than 10 characters is not allowed!"

after 
sendConsoleMsg(peer, "`4Sorry, but world names with more than 10 characters is not allowed!");

**Comment by kikou12** [comment]
change at xampp or visual studio?

**Comment by mar4ello6** [comment]
> before
> sendConsoleMsg(peer, "`4Sorry, but world names with more than 10 characters is not allowed!"
> 
> after
> sendConsoleMsg(peer, "`4Sorry, but world names with more than 10 characters is not allowed!");

Thanks, I forgot about this.



> change at xampp or visual studio?

It is for server code, Visual Studio.

**Comment by Yoayao** [comment]
what if my sendinventory are gone where i can put the {

**Comment by GrowtopiaNoobs** [comment]
Wouldn't it be better to set it like to 20 characters or something? How much does GT allow?

**Comment by playingo** [comment]
how about limiting the world creation of a player to a certain amount of worlds? same as gt does.

**Comment by playingo** [comment]
plus maybe captcha its bypassible but still.

**Comment by mar4ello6** [comment]
Now it is blocking worlds with name length more than GT allow.

**Comment by GrowtopiaNoobs** [comment]
@playingo It would be good, but I don't know if it won't be annoying for player to still see captcha and that after certain number of worlds created they won't be allowed to make more and I have no idea what will be good number for player, but good number to block attack.

**Comment by GrowtopiaNoobs** [comment]
@mar4ello6 Good job! :+1:

**Pull request merged**
