### PR TITLE
growmoji

### PR DESCRIPTION
**Pull request by NotDark**
(troll) no work i no sure why

### CODE REVIEW

**Comment by GrowtopiaNoobs** [comment]
Only troll doesn't work and others are fine?

**Comment by ilyn1337** [comment]
Set appendInt to 0, set all 0& to 1&

**Comment by fargamerhd** [comment]
for some reason i cant use this it when i try any to use any it show ? not the emoji any one know how to fix ?

**Comment by NotDark** [comment]
> Only troll doesn't work and others are fine?

Yes only troll

**Comment by ZentaiZber** [comment]
its return "?" how to fix?

**Pull request merged**
