### PR TITLE
checkpoint system by cmd

### PR DESCRIPTION
**Pull request by cmdocmd**
checkpoints

### CODE REVIEW

**Comment by playingo** [comment]
copyrights and the code itself (originally made by me) bought by playingo for a couple dls bruh bruh**

**Comment by cmdocmd** [comment]
hmm i bought the copyright from u so the code for me

**Comment by cmdocmd** [comment]
btw 
press ctrl + f 
search this 
cout << "Ugh, unsupported item " << tile << endl;
 u will find tile == 410 delete it so u can place checkpoints

**Comment by ardakurucim** [comment]
does this do yellow thingie on checkpoint? also there is no punch effect void on this source

**Comment by cmdocmd** [comment]
well no its only checkpoint when u move on it u should respawn

**Comment by cmdocmd** [comment]
u should make when exit the world usedCP == false; so it remove the checkpoint x and y

**Comment by cmdocmd** [comment]
credit to playingo he helped me with it

**Comment by flossboss** [comment]
Fix "sendPuncheffect"

**Comment by Deveytv** [comment]
@cmdocmd or @flossboss How to fix this 1 error is annoying huh can tell me how to fix it? 
image

**Comment by cmdocmd** [comment]
dude try to add { or } one of this

**Comment by NotDark** [comment]
if (data2->packetType == 7){

if ( block is checkpoint){
use setrespawnpos thing here
}
}

for checkpoint light effect

**Comment by FocusedSG** [comment]
>and btw search for  ...

@cmdocmd Not that way. By removing ``sendPlayerLeave`` from ``packetType 7``, players will be unable to leave via the Main Door. Instead, you can check which block the player is standing infront of. If it’s a Main Door, then ``sendPlayerLeave``, else send checkpoint stuff.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Pull request closed without merging**
