### PR TITLE
Make own/adding own item On your own gtps 

### PR DESCRIPTION
**Pull request by Deveytv**
there file for adding the item : 
[item_definitions.txt.txt](https://github.com/GrowtopiaNoobs/GrowtopiaServer/files/3401061/item_definitions.txt.txt)

There are Converter the ur own item to rttex : https://tools.cernodile.com/rttex.html
  Hope is helping you :) and understand how to do

### CODE REVIEW

**Comment by SurekingIGTPS** [comment]
Sorry i just want to helping u guys but idk how pull request :v Hope it's helping you

**Comment by FuzionVapes** [comment]
Help yourself on learning how to speak proper english

**Comment by ilyn1337** [comment]
bullshit, it wont do anything

**Comment by NotDark** [comment]
> there file for adding the item :
> [item_definitions.txt.txt](https://github.com/GrowtopiaNoobs/GrowtopiaServer/files/3401061/item_definitions.txt.txt)
> 
> There are Converter the ur own item to rttex : https://tools.cernodile.com/rttex.html
> Hope is helping you :) and understand how to do

That dont do anything

**Comment by GrowtopiaNoobs** [comment]
Well, it won't help with anything, just how others said. Closing

**Pull request closed without merging**
