### PR TITLE
Fixing when player login crash word

### PR DESCRIPTION
**Pull request by WoofHax**

### CODE REVIEW

**Comment by playingo** [comment]
everyone knows this and its used to be on my source a long time ago and it used the prefix "__"

**Comment by herothedev** [comment]
if u use linux no need this

**Comment by flossboss** [comment]
b1g!!11!!!1!

**Comment by GrowtopiaNoobs** [comment]
Good job, but I won't merge this, because this would break backwards compatibility and I would also recommend to use prefix `__`.

**Pull request closed without merging**
