### PR TITLE
Fixing no text spam

### PR DESCRIPTION
**Pull request by flossboss**
Credits to @playingo :v
I don't think this works for linux.

### CODE REVIEW

**Comment by cmdocmd** [comment]
the problem is i posted this in pull request long time ago HAHA

**Comment by playingo** [comment]
not with the space fix @cmd dont lie but other than that

**Comment by flossboss** [comment]
Thonk

**Comment by ardakurucim** [comment]
wew

**Comment by Cojeb** [comment]
#1110

**Pull request closed without merging**
