### PR TITLE
Account hack and ban bypass fix.

### PR DESCRIPTION
**Pull request by playingoDEERUX**

### CODE REVIEW

**Comment by playingoDEERUX** [comment]
Please use the latest commit because the first one had the hasLogon check code placed in the wrong place. It should be checked before entering a world and not when receiving a message type value of 3.
So use the latest one, as that one has it in the correct position (when entering the world), sorry for that.
This is an important fix in my opinion!

**Comment by DrOreo002** [comment]
Great job, this should be merged 👍

**Comment by raiterjaki** [comment]
> Great job, this should be merged 👍

not great job to him. He saw it in group

**Comment by playingoDEERUX** [comment]
@raiterjaki same as you saw pixel worlds dev server in the group :)

**Comment by GrowtopiaNoobs** [comment]
Good job :+1:

**Pull request merged**
