### PR TITLE
Fix for wrenching not only locks.

### PR DESCRIPTION
**Pull request by SecretHax**
In the old code you could wrench other items and the lock Public/Private dialogue opened up ( after choosing it changed the world isPublic, not item's ). In my code you can wrench ONLY locks and that's better.

### CODE REVIEW

**Comment by ritzysw** [comment]
I highly suggest you to stop trolling and spamming

**Comment by SecretHax** [comment]
> I highly suggest you to stop trolling and spamming

Hmm? This is just a bug patch for locking system. And I highly suggest you to stop attacking my vps or I will take legal actions against you.

**Comment by ritzysw** [comment]
1. You are spamming
2. Creation of growtopia private servers is illegal third party redistribution which can get you in trouble if ubisoft decides to take action against people like you
3. Good luck "taking legal actions against me for """attacking your vps""""
4. You are literally using word "or" instead of ||, which also shows how incompetent you are

**Comment by SecretHax** [comment]
> 1. You are spamming
> 2. Creation of growtopia private servers is illegal third party redistribution which can get you in trouble if ubisoft decides to take action against people like you
> 3. Good luck "taking legal actions against me for """attacking your vps""""
> 4. You are literally using word "or" instead of ||, which also shows how incompetent you are



> 1. You are spamming
> 2. Creation of growtopia private servers is illegal third party redistribution which can get you in trouble if ubisoft decides to take action against people like you
> 3. Good luck "taking legal actions against me for """attacking your vps""""
> 4. You are literally using word "or" instead of ||, which also shows how incompetent you are

Well, You had a server, so you can get in trouble too.
I'm not spamming at all, just made 2 pull requests right now.
It doesn't make any difference if you use "or" instead of "||".
Thanks for calling me incompetent sir. At least I know what manners are.

**Comment by ritzysw** [comment]
So you are implying that I'll get in trouble for having a server 2-3 months ago? That's epic
Also no, you don't know what manners are

**Comment by SecretHax** [comment]
>So you are implying that I'll get in trouble for having a server 2-3 months ago? That's epic ...

@ritzysw Speechless.. You are just pathetic.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ritzysw** [comment]
Pussied out so quickly, good skid
And this isn't place to fight, so once again - stop spamming

**Comment by SecretHax** [comment]
>Pussied out so quickly, good skid ...

@ritzysw You started fighting and now you are saying „This isn’t a place to fight”
You did many illegal things such as leaking ubisoft’s database or starting a private server and I can prove that.
Also, stop offending me.
I’m sorry if I made spam, but I’m new to discord so hope you understand my mistakes.
Topic solved. 


<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Pull request merged**
