### PR TITLE
Update enet server test.cpp

### PR DESCRIPTION
**Pull request by raiterjaki**
instead of creating a void for each function like packet::consolemessage I made a better way where you can just do buildPackett(peer, "OnConsoleMessage", "test");

### CODE REVIEW

**Comment by cmdocmd** [comment]
tbh its a bad idea because not all packets are the same way of use

**Comment by noobes1337** [comment]
i'm supposed to add everything buildPacketttttt? h1ghsky

**Comment by xXAbood** [comment]
useless

**Comment by raiterjaki** [comment]
retards are mad

**Comment by Alexander9673** [comment]
no offense, this is really useful. If you're planning to add this feature, i suggest it to be much more customizable. Because this is basically just `packetEnd(appendString(appendString(createPacket(), "PacketName?", "something here."));`. Yes you are building a packet, but overall it's not that good. Needs more customizability. Maybe you can do something like this:
```cpp
packet.create() // does the create packet
  .string("OnConsoleMessage")
  .string("Message")
  .end();
``` which would be the equivalent of `packetEnd(appendString(appendString(createPacket(), "OnConsoleMessage", "Message"));`

**Comment by raiterjaki** [comment]
> no offense, this is really useful. If you're planning to add this feature, i suggest it to be much more customizable. Because this is basically just `packetEnd(appendString(appendString(createPacket(), "PacketName?", "something here."));`. Yes you are building a packet, but overall it's not that good. Needs more customizability. Maybe you can do something like this:
> 
> ```c++
> packet.create() // does the create packet
>   .string("OnConsoleMessage")
>   .string("Message")
>   .end();
> ```
> 
> which would be the equivalent of `packetEnd(appendString(appendString(createPacket(), "OnConsoleMessage", "Message"));`

I made it because it is simple you don't have to write that long thing all the time.

**Comment by MoanHawks** [comment]
> useless

i agree with you this code is useless better use variable argument lists

**Pull request closed without merging**
