### PR TITLE
/news with txt file

### PR DESCRIPTION
**Pull request by cmdocmd**

### CODE REVIEW

**Comment by GrowtopiaNoobs** [comment]
Good job :+1: But your code is missing removing of `\r` character, caching of news content and also commands to show news.

**Comment by cmdocmd** [comment]
you mean if there is /r should be removed ?

**Comment by GrowtopiaNoobs** [comment]
Yes, windows use sequence `\r\n` for new lines, but Growtopia uses only `\n`.

**Comment by GrowtopiaNoobs** [comment]
Closing this as you opened new PR #1317.

**Pull request closed without merging**
