### PR TITLE
Items.dat hash updated to latest one

### PR DESCRIPTION
**Pull request by ilyn1337**
Nothing to say.

### CODE REVIEW

**Comment by SecretHax** [comment]
Why are you still using ubisoft server? You can easily host the plugins ur vps. Wanna learn? Contact me on discord: SecretHax#0001.
Then you don’t need their updates and new hash

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ilyn1337** [comment]
@SecretHax Trypo discord id... mine is: noob(HASHTAG)9321

**Comment by CrazyMonkey313** [comment]
Im stupid but does this add all new things from 3days ago?

**Comment by Mempler** [comment]
Yes, as always.

**Pull request merged**
